Make Polylines immutable
To make Polylines work as keys in dicts, we cannot use dataclass because
those are mutable and Python doesn't like using them as keys:

    TypeError: unhashable type: 'Polyline'

To fix this, we replace `dataclass` with `typing.NamedTuple` because
tuples are hashable.